export enum Browser {
  AmazonSilk = "Amazon Silk",
  Android = "Android Browser",
  Bada = "Bada",
  Blackberry = "BlackBerry",
  Chrome = "Chrome",
  Chromium = "Chromium",
  Electron = "Electron",
  Epiphany = "Epiphany",
  Firefox = "Firefox",
  Focus = "Focus",
  Generic = "Generic",
  GoogleSearch = "Google Search",
  Googlebot = "Googlebot",
  InternetExplorer = "Internet Explorer",
  KMeleon = "K-Meleon",
  Maxthon = "Maxthon",
  Edge = "Microsoft Edge",
  MZ = "MZ Browser",
  Naver = "NAVER Whale Browser",
  Opera = "Opera",
  OperaCoast = "Opera Coast",
  PhantomJS = "PhantomJS",
  Puffin = "Puffin",
  QupZilla = "QupZilla",
  QQ = "QQ Browser",
  QQLite = "QQ Browser Lite",
  Safari = "Safari",
  Sailfish = "Sailfish",
  SamsungInternetForAndroid = "Samsung Internet for Android",
  SeaMonkey = "SeaMonkey",
  Sleipnir = "Sleipnir",
  Swing = "Swing",
  Tizen = "Tizen",
  UCBrowser = "UC Browser",
  Vivaldi = "Vivaldi",
  WebOS = "WebOS Browser",
  WeChat = "WeChat",
  Yandex = "Yandex Browser",
}

export enum Platform {
  Tablet = "tablet",
  Mobile = "mobile",
  Desktop = "desktop",
  Tv = "tv",
}

export enum OS {
  WindowsPhone = "Windows Phone",
  Windows = "Windows",
  MacOS = "macOS",
  iOS = "iOS",
  Android = "Android",
  WebOS = "WebOS",
  BlackBerry = "BlackBerry",
  Bada = "Bada",
  Tizen = "Tizen",
  Linux = "Linux",
  ChromeOS = "Chrome OS",
  PlayStation4 = "PlayStation 4",
  Roku = "Roku",
}

export enum Engine {
  EdgeHTML = "EdgeHTML",
  Blink = "Blink",
  Trident = "Trident",
  Presto = "Presto",
  Gecko = "Gecko",
  WebKit = "WebKit",
}
