export enum Browser {
  AmazonSilk = "amazon_silk",
  Android = "android",
  Bada = "bada",
  Blackberry = "blackberry",
  Chrome = "chrome",
  Chromium = "chromium",
  Electron = "electron",
  Epiphany = "epiphany",
  Firefox = "firefox",
  Focus = "focus",
  Generic = "generic",
  Googlebot = "googlebot",
  GoogleSearch = "google_search",
  InternetExplorer = "ie",
  KMeleon = "k_meleon",
  Maxthon = "maxthon",
  Edge = "edge",
  MZ = "mz",
  Naver = "naver",
  Opera = "opera",
  OperaCoast = "opera_coast",
  PhantomJS = "phantomjs",
  Puffin = "puffin",
  QupZilla = "qupzilla",
  QQBrowser = "qq",
  QQBrowserLite = "qqlite",
  Safari = "safari",
  Sailfish = "sailfish",
  SamsungInternet = "samsung_internet",
  SeaMonkey = "seamonkey",
  Sleipnir = "sleipnir",
  Swing = "swing",
  Tizen = "tizen",
  UCBrowser = "uc",
  Vivaldi = "vivaldi",
  WebOS = "webos",
  WeChat = "wechat",
  Yandex = "yandex",
}

export enum Platform {
  Tablet = "tablet",
  Mobile = "mobile",
  Desktop = "desktop",
  Tv = "tv",
}

export enum OS {
  WindowsPhone = "WindowsPhone",
  Windows = "Windows",
  MacOS = "MacOS",
  iOS = "iOS",
  Android = "Android",
  WebOS = "WebOS",
  BlackBerry = "BlackBerry",
  Bada = "Bada",
  Tizen = "Tizen",
  Linux = "Linux",
  ChromeOS = "ChromeOS",
  PlayStation4 = "PlayStation4",
  Roku = "Roku",
}

export enum Engine {
  EdgeHTML = "EdgeHTML",
  Blink = "Blink",
  Trident = "Trident",
  Presto = "Presto",
  Gecko = "Gecko",
  WebKit = "WebKit",
}
